import axios from 'axios'
import Head from 'next/head'
import { useEffect, useReducer } from 'react'
import Button from '../components/Button'
import Card from '../components/Card'
import { peopleReducers } from '../reducers/peopleReducers'

export default function Home() {
  const [state, dispatch] = useReducer(peopleReducers, {
    people: [],
    next_page: null,
  })

  const peopleApi = async (url) => {
    const { data } = await axios.get(url)
    dispatch({
      type: "ADD_PEOPLE",
      payload: [...state.people, ...data.results]
    })
    dispatch({
      type: "ADD_NEXT_PAGE",
      payload: data.next
    })
  }

  useEffect(() => {
    peopleApi('https://swapi.dev/api/people')
  }, [])

  return (
    <div style={{ backgroundImage: `url(/images/Desktop.svg)` }}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>


      <main className="mx-auto my-10" >
        <div className="grid gap-12 grid-cols-1 md:grid-cols-2 lg:grid-cols-3">
          {state.people.map((item, index) =>
            <Card id={item.url.match(/\d+/)[0]} item={item} key={item.birth_year + index} />
          )}
        </div>
        <div className="mt-10 mx-auto w-full">
          {state.next_page ?
            <Button
              onClick={() => { peopleApi(state.next_page) }}
            >
              Load More
            </Button> :
            <div className="text-white w-full text-center text-2xl font-bold">
              {state.people.length === 0 ? "Loading Please Wait" : "End of the list"}
            </div>}
        </div>
      </main>

      {/* <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer> */}
    </div>
  )
}
